### ISSUE TITLE
[question] Reason for skipping `base-passwd` and `packagegroup-*` packages when generating SPDX documents

### ISSUE THREAD

**Issue by PatSche** [Wind-River/meta-wr-sbom#3]
Hi there!

I have a question about the filtering of packages/recipes.

In the files [`sls-create-spdx.bbclass`](https://github.com/Wind-River/meta-wr-sbom/blob/3bcd4964b2d306a8c1679ed483e92b6c9b7c14e2/classes/sls-create-spdx.bbclass#L1065C1-L1068C21) and [`gen_spdx.py`](https://github.com/Wind-River/meta-wr-sbom/blob/3bcd4964b2d306a8c1679ed483e92b6c9b7c14e2/tools/gen_spdx.py#L453C1-L456C21), there are Python loops that iterate through the package/recipe dictionaries for the final Software Bill of Materials (SBOM). Within these loops, there's a part that skips packages starting with `packagegroup-` or it's `base-passwd`.

Here's how it looks in Python:
```python
for name in recipeDict.keys():
    if name.startswith("packagegroup-") or name == "base-passwd":
        continue
```

Could you clarify the specific purpose behind skipping these packages/recipes?
The code comments or documentation don't provide clear reasoning for this exclusion.

**Comment by hmiwindriver** [comment]
Some virtual and empty packages are consider exclude from the final SBOM.
While, the 'base-passwd' is not necessary to be excluded as a special package.

[940c2fe676e371465c65207b36b7f0b579bbad64](https://github.com/Wind-River/meta-wr-sbom/commit/940c2fe676e371465c65207b36b7f0b579bbad64)

**Comment by hmiwindriver** [comment]
[940c2fe676e371465c65207b36b7f0b579bbad64](https://github.com/Wind-River/meta-wr-sbom/commit/940c2fe676e371465c65207b36b7f0b579bbad64)
